export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_ENTRIES_START = 'FETCH_ENTRIES_START';
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS';
export const FETCH_ENTRIES_FAIL = 'FETCH_ENTRIES_FAIL';

export const ENTRY_REMOVE = 'ENTRY_REMOVE';
