export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';

export const ENTRIES_FETCH = 'ENTRIES_FETCH';
export const FETCH_ENTRIES_START = 'FETCH_ENTRIES_START';
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS';
export const FETCH_ENTRIES_FAIL = 'FETCH_ENTRIES_FAIL';

export const ENTRIES_CLEAR = 'ENTRIES_CLEAR';

export const ENTRY_ADD = 'ENTRY_ADD';
export const ENTRY_REMOVE = 'ENTRY_REMOVE';
export const ENTRY_ACTION_START = 'ENTRY_ACTION_START';
export const ENTRY_ACTION_SUCCESS = 'ENTRY_ACTION_SUCCESS';
export const ENTRY_ACTION_FAIL = 'ENTRY_ACTION_FAIL';
